# Generated by Django 5.2.7 on 2026-05-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Completado', 'Completado'), ('Entregado', 'Entregado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
