# Generated by Django 5.2.7 on 2026-05-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_accesorio_stock_alter_accesorio_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='fecha',
            new_name='fecha_venta',
        ),
        migrations.AddField(
            model_name='telefono',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Completado', 'Completado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
