# Generated by Django 5.2.8 on 2026-05-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_rename_fecha_venta_fecha_venta_telefono_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='telefonos/'),
        ),
    ]
