# Generated by Django 5.2.8 on 2026-06-10 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_reparacion_descripcion_reparacion_reparacion_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='descripcion_reparacion',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='problema',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='caracteristicas',
            field=models.TextField(blank=True, verbose_name='Características del equipo'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='diagnostico',
            field=models.TextField(blank=True, verbose_name='Diagnóstico del técnico'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='proceso_realizado',
            field=models.TextField(blank=True, verbose_name='Proceso realizado'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='razon_visita',
            field=models.TextField(blank=True, verbose_name='Razón de visita'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completado', 'Completado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.telefono'),
        ),
    ]
