# Generated by Django 5.2.8 on 2026-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_remove_reparacion_descripcion_reparacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='accesorios_recibidos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='defecto_cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='informacion_taller',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='serie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='tipo_equipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='caracteristicas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='proceso_realizado',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='razon_visita',
            field=models.TextField(blank=True),
        ),
    ]
