# Generated by Django 5.2.8 on 2026-06-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_reparacion_accesorios_recibidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='caracteristicas',
            field=models.TextField(blank=True, verbose_name='Características del equipo'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='defecto_cliente',
            field=models.TextField(blank=True, verbose_name='Defecto según cliente'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='diagnostico',
            field=models.TextField(blank=True, verbose_name='Diagnóstico del técnico'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='proceso_realizado',
            field=models.TextField(blank=True, verbose_name='Proceso realizado'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='razon_visita',
            field=models.TextField(blank=True, verbose_name='Razón de visita'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='tipo_equipo',
            field=models.CharField(max_length=100),
        ),
    ]
