# Generated by Django 5.2.8 on 2026-06-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_remove_reparacion_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='tipo_equipo',
        ),
    ]
