# Generated by Django 5.2.8 on 2026-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_remove_reparacion_tipo_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='accesorios/'),
        ),
    ]
