# Generated by Django 5.2.8 on 2026-06-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_accesorio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='cotizacion_servicio',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle de cotización'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='precio_cotizacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio cotización'),
        ),
    ]
